language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/dewi.ino

install:
    - pip install -U platformio

script:
    - platformio ci --board=uno --lib=lib

notifications:
    slack:
      rooms:
        secure: DiHEt0Ntwv23Qmf6mVH50iu4Pewqx1Bk35ebKR/x6TL7aL85Zr4LeZaeltvx78DPD5LPpaLS8GGCTTUC4T/VGP0bOgvSCg0ods9ENDHJdCY7uvzK8wPaKtZ0NT41xjPpw/SqKjVddj1rWQ1xTpR61l0tSYunQEPVQbFUyUbmDyc=
